### ISSUE TITLE
Upload should be disabled by default

### ISSUE THREAD

**Issue by ax42** [randsleadershipslack/statistics#2]
i.e. the reverse of the current behaviour.  As more and more people play with the code, we don't want to be spamming the slack by accident.

**Comment by wpeterson** [comment]
Agreed.  I was surprised to see I generated/uploaded a report the first time I ran the tool :)

Fixed in https://github.com/randsleadershipslack/statistics/commit/818bbced0f471ff41e6edcc544ec5b90fb7cd9d6
