### ISSUE TITLE
Refactor --no-report flag

### ISSUE THREAD

**Issue by ax42** [randsleadershipslack/statistics#6]
My use case is that I would like to 

- download the messages
- produce the statistics json 
- NOT produce the html
- Still save the json

I would suggest that there should be a --no-html to not produce the html report, but that still saves the json into the zip.  Downside of this is that you can no longer rely on the zip file containing the html.

At the same time, I would refactor the code so that the htmlmin/jinja2 libraries are only imported if the html is requested (to cut down on dependencies if all you want to do is download).

Happy to hear comments before I implement.

**Comment by dlovitch** [comment]
Makes sense to me 👍

**Comment by ax42** [comment]
Closed with merge above.
